export const SET_GLOBAL_VARIABLE = 'SET_GLOBAL_VARIABLE';
export const SET_GLOBAL_VARIABLE_SUCCESSFUL = 'SET_GLOBAL_VARIABLE_SUCCESSFUL';
export const SET_GLOBAL_VARIABLE_FAILED = 'SET_GLOBAL_VARIABLE_FAILED';


